AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.1

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
